apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    role: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pv-claim
spec:
  storageClassName: manual
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
        storage: 1Gi