apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-service
  ports:
    - port: 80
      targetPort: 6379
      nodePort: 31079
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis-demo
spec:
  selector:
    app: redis-demo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  selector:
    app: mongo-service
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30090
      protocol: TCP
  type: NodePort

